#!/usr/bin/env node
/* Concatenate CSS modules into rankme.css (no @import, production bundle).
   Edit _*.css only. Never hand-edit rankme.css. */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const files = [
  '_tokens.css',
  '_chrome.css',
  '_hero.css',
  '_tier.css',
  '_battle.css',
  '_home.css',
  '_account.css',
  '_create.css',
];
const BANNER = '/* AUTO-GENERATED by css/build.js — edit _*.css, then: node css/build.js */\n\n';

const missing = files.filter((f) => !fs.existsSync(path.join(dir, f)));
if (missing.length) {
  console.error('Missing modules:', missing.join(', '));
  process.exit(1);
}

const body = files
  .map((f) => fs.readFileSync(path.join(dir, f), 'utf8').replace(/\s+$/, '') + '\n')
  .join('\n');
const out = BANNER + body;
fs.writeFileSync(path.join(dir, 'rankme.css'), out);
console.log('wrote css/rankme.css (' + out.length + ' bytes from ' + files.length + ' modules)');
