#!/usr/bin/env node
/* Concatenate js/editor/_*.js into js/app.js.
   Edit js/editor/_*.js only. Never hand-edit app.js. */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const editor = path.join(dir, 'editor');
const inner = [
  '_core.js',
  '_render.js',
  '_drag.js',
  '_ui.js',
  '_persist.js',
  '_export.js',
  '_leave.js',
  '_boot.js',
];
const cta = '_battle-cta.js';
const BANNER = '/* AUTO-GENERATED by js/build-app.js — edit js/editor/_*.js, then: node js/build-app.js */\n\n';

const missing = inner.concat(cta).filter((f) => !fs.existsSync(path.join(editor, f)));
if (missing.length) {
  console.error('Missing editor modules:', missing.join(', '));
  process.exit(1);
}

const body = inner
  .map((f) => fs.readFileSync(path.join(editor, f), 'utf8').replace(/\s+$/, '') + '\n')
  .join('\n');
const battleCta = fs.readFileSync(path.join(editor, cta), 'utf8').replace(/\s+$/, '') + '\n';
const out = BANNER + '(function(){\n"use strict";\n\n' + body + '\n})();\n\n' + battleCta;
fs.writeFileSync(path.join(dir, 'app.js'), out);
console.log('wrote js/app.js (' + out.length + ' bytes from ' + (inner.length + 1) + ' modules)');
